# Generated by Django 3.2.12 on 2023-09-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0005_meter_meter_number'),
        ('meter_reading', '0006_remove_meter_meter_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter.meter'),
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
    ]
