# Generated by Django 3.2.12 on 2023-09-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0006_auto_20230917_1823'),
        ('meter_reading', '0007_auto_20230917_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter.meter'),
        ),
    ]
