# Generated by Django 3.2.12 on 2023-09-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0007_meter_current_reading'),
        ('meter_reading', '0009_alter_meterreading_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter.meter'),
        ),
    ]
