# Generated by Django 3.2.12 on 2023-09-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_alter_meter_meter_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='current_reading',
            field=models.PositiveIntegerField(),
        ),
    ]
