# Generated by Django 3.2.12 on 2023-09-13 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_alter_meter_current_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='current_reading',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
