# Generated by Django 3.2.12 on 2023-09-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0005_meter_meter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='current_reading',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_number',
        ),
    ]
