# Generated by Django 3.2.12 on 2023-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0006_auto_20230917_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='current_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
