# Generated by Django 4.2.4 on 2023-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_units', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
