# Generated by Django 3.2.12 on 2023-09-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_auto_20230913_1112'),
        ('unit_sharing', '0003_alter_unitsharing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsharing',
            name='recipient_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_received', to='meter.meter'),
        ),
        migrations.AddField(
            model_name='unitsharing',
            name='sender_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_sent', to='meter.meter'),
        ),
    ]
