# Generated by Django 4.2.4 on 2023-09-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_sharing', '0004_auto_20230917_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitsharing',
            name='recipient_meter',
        ),
        migrations.RemoveField(
            model_name='unitsharing',
            name='sender_meter',
        ),
    ]
