# Generated by Django 4.2.4 on 2023-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
