# Generated by Django 4.2.4 on 2023-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsharing',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
