# Generated by Django 3.2.12 on 2023-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='current_reading',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
