# Generated by Django 4.2.5 on 2023-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_reading', '0002_alter_meterreading_current_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
