# Generated by Django 3.2.12 on 2023-09-17 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meter_reading', '0003_alter_meterreading_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_serial_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter_reading.meter'),
        ),
    ]
