# Generated by Django 3.2.12 on 2023-09-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_reading', '0005_meter_meter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='meter_serial_number',
        ),
    ]
