name: Django CI/CD
on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run:
        pip freeze>requirements.txt
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Check Syntax
      run: pre-commit run --all-files
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Check Syntax
      run: pre-commit run --all-files
    - name: Run Migrations
      run: python3 manage.py migrate
    - name: Run tests
      run:
        python manage.py test
